// Code generated by MockGen. DO NOT EDIT.
// Source: ./house_service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	request "backend-bootcamp-assignment-2024/internal/model/dto/request"
	entity "backend-bootcamp-assignment-2024/internal/model/entity"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockHouseRepository is a mock of HouseRepository interface.
type MockHouseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockHouseRepositoryMockRecorder
}

// MockHouseRepositoryMockRecorder is the mock recorder for MockHouseRepository.
type MockHouseRepositoryMockRecorder struct {
	mock *MockHouseRepository
}

// NewMockHouseRepository creates a new mock instance.
func NewMockHouseRepository(ctrl *gomock.Controller) *MockHouseRepository {
	mock := &MockHouseRepository{ctrl: ctrl}
	mock.recorder = &MockHouseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHouseRepository) EXPECT() *MockHouseRepositoryMockRecorder {
	return m.recorder
}

// CreateHouse mocks base method.
func (m *MockHouseRepository) CreateHouse(ctx context.Context, house request.House) (*entity.House, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHouse", ctx, house)
	ret0, _ := ret[0].(*entity.House)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateHouse indicates an expected call of CreateHouse.
func (mr *MockHouseRepositoryMockRecorder) CreateHouse(ctx, house interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHouse", reflect.TypeOf((*MockHouseRepository)(nil).CreateHouse), ctx, house)
}

// UpdateHouse mocks base method.
func (m *MockHouseRepository) UpdateHouse(ctx context.Context, houseId int32, updateTime time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHouse", ctx, houseId, updateTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateHouse indicates an expected call of UpdateHouse.
func (mr *MockHouseRepositoryMockRecorder) UpdateHouse(ctx, houseId, updateTime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHouse", reflect.TypeOf((*MockHouseRepository)(nil).UpdateHouse), ctx, houseId, updateTime)
}
